name: proxet
description: A sample command-line application with basic argument parsing.
version: 1.0.1
repository: https://github.com/rivethorn/proxet

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
